# Server config
server.port=8080

# Application config
WORKER_LOCAL_URL=${LOCAL_WORKER_URL:https://headboard-flavored-counting.ngrok-free.dev}
WORKER_CLOUD_URL=${CLOUD_WORKER_URL:https://ai-video-assistant-39ar.onrender.com}

# Database (Supabase Postgres)
spring.datasource.url=${SUPABASE_DB_URL:jdbc:postgresql://localhost:5432/postgres}
spring.datasource.username=${SUPABASE_DB_USER:postgres}
spring.datasource.password=${SUPABASE_DB_PASSWORD:secret}
spring.datasource.hikari.maximum-pool-size=3
spring.datasource.hikari.minimum-idle=1

# JPA Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Internal API Key (used for sending callback requests)
INTERNAL_API_KEY=${INTERNAL_API_KEY:change_me_in_production}

# Spring Security OAuth2 Resource Server Configuration (Clerk)
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://possible-lacewing-4977.clerk.accounts.dev
